### ISSUE TITLE
Sharing options model amongst multiple selectize

### ISSUE THREAD

**Issue by miketeix** [machineboy2045/angular-selectize#63]
The $watch on scope.options inside of onInitialize wasn't firing for me. 
``` javascript
Line 106
        scope.$watch('options', function(){
          selectize.clearOptions();
          selectize.addOption(scope.options)
          selectize.setValue(scope.ngModel)
        }, true);
```
I believe it was because the reference $scope.options in my controller was being overwritten from within angular-selectize here:
``` javascript
Line 92 
scope.options = generateOptions( (scope.options || config.options || scope.ngModel).slice() );
```
I'm going to submit a pull-request with the changes that worked for me - would like to know what you think. Thanks again for this clean directive, Cheers!

**Comment by PhiLhoSoft** [comment]
This fix breaks when combined with mine, allowing to provide options as an object. Since the object doesn't have (likely) a splice() method, I get a TypeError.
I have a fix, tested in http://plnkr.co/edit/8OuwS7?p=preview on both cases (array and object, one on persons, the other on e-mails).
Note: it includes another change, related to #69, but they are distinct.

Basically: I rename generateOptions to normailzeOptions, because it changes the data in place.
Instead of `return $.map(...);` I do:

        angular.forEach(data, function(opt, key) {
            if (typeof opt === 'string') {
                data[key] = createItem(opt);
            }
        });
        return data;

When I have `generateOptions(scope.ngModel)` I replace it with `normalizeOptions(angular.copy(scope.ngModel)`, ie. I do the copy on the call site.
Thus, the main change becomes:

      if (scope.options) {
        // replace string options with generated options while retaining a reference to the same array
        normalizeOptions(scope.options);
      } else {
        // default options = [ngModel] if no options specified
        scope.options = normalizeOptions(angular.copy(scope.ngModel));
      }

I can do a pull request with these changes if you want.
