### ISSUE TITLE
Integer value fields are converted to strings on selection

### ISSUE THREAD

**Issue by q-state** [machineboy2045/angular-selectize#77]
I've noticed integer values are converted to strings when they are selected - but only when maxItems > 1. 

I changed the e-mail demo in plunkr so that the email values were just sequential integers, but when they are selected the ngModel is ["1", "2"].

Is there a reason for this behavior?

**Comment by PhiLhoSoft** [comment]
I was curious, so I debugged the code to see where the conversion comes from. It can be seen in the simple "Single Item Select" demo, too.

The "problem" comes from Selectize itself, not from angular-selectize...
Anyway, I think the culprit is in the line `value = $target.attr('data-value');` (at line 1670 of the standalone version I use, in onOptionSelect callback). As you can see, Selectize gets back the value from a data attribute of the generated HTML, so it has no way to know if the value was integer (or float!) when it was created.

Now, of course, it is rather trivial to convert back the values to integers, when you need them.

Note: I don't think it is related to the maxItems setting.
