### ISSUE TITLE
ng-show is not working

### ISSUE THREAD

**Issue by phanhongphucit** [machineboy2045/angular-selectize#85]
As the title described

**Comment by PhiLhoSoft** [comment]
Indeed, it just adds a ng-hide class on the `selectize` tag, but it just adds `display: none` which is already on the tag...
I suppose the directive should watch this attribute and react accordingly.

Workaround: use `ng-if`. Not exactly the same thing, but might be useful in some cases. Since Angular removes the `selectize` component from the Dom, it effectively removes also the associated elements.

**Comment by Uelb** [comment]
Same issue here... Thank you for the ng-if workaround

**Comment by mohitjee15** [comment]
@PhiLhoSoft please close the issue if it resolved.

**Comment by PhiLhoSoft** [comment]
@mohitjee15 I cannot: I haven't created the issue, and I have no control over the project.
Beside, the issue is not resolved. Support for ngShow can be added to the control, can be useful.

**Comment by machineboy2045** [comment]
@PhiLhoSoft another solution might be to add a template to the directive, that would wrap a div around the div that Selectize gets applied to. What do you think?
